### ISSUE TITLE
How to run the file?

### ISSUE THREAD

**Issue by ShaneAbara** [Panzer1119/Supreme-Bot#1]
I need help on running it

**Comment by Panzer1119** [comment]
What file do you mean? You can download the source and compile it on your computer. But the bot is work in progress.

**Comment by ShaneAbara** [comment]
Whenever I compile it it's looking for .exe file

**Comment by Panzer1119** [comment]
Hmm i don't know what the problem could be. But make sure you compile the "src" and "Supreme-Bot-Plugins/src" folder separately, because the "src" folder is the source for the bot and the other is a test for plugins that I may finish in the future.

**Comment by Panzer1119** [comment]
I have added a compiled version of the Bot, so you can run it directly. But i don't know if it's working, because maybe some extra files are missing/not created yet. But you can try it anyway.
